(()=>{"use strict";
const D="central-estudos:density-v5",T="central-estudos:technical-cards-v5",O="central-estudos:catalog-order-v4",S="central-estudos:catalog-sort-v4",F="central-estudos:favorites-v4",FO="central-estudos:focus-project",$=id=>document.getElementById(id),panel=$("preferences-panel"),density=$("preference-density"),technical=$("preference-technical"),orderList=$("preferences-order-list"),reset=$("preferences-reset"),status=$("preferences-status"),grid=$("projects-grid"),catalogSort=$("catalog-sort");
if(!panel||!density||!technical||!orderList||!reset||!grid)return;document.documentElement.classList.add("preferences-enabled");let storageWritable=true,renderingOrder=false;
function readText(k){try{return localStorage.getItem(k)}catch{storageWritable=false;return null}}function writeText(k,v){try{localStorage.setItem(k,v);return true}catch{storageWritable=false;return false}}function removeKey(k){try{localStorage.removeItem(k);return true}catch{storageWritable=false;return false}}function readJson(k,f){const r=readText(k);if(!r)return f;try{return JSON.parse(r)??f}catch{removeKey(k);return f}}const writeJson=(k,v)=>writeText(k,JSON.stringify(v));
function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}function announce(m){if(status)status.textContent=storageWritable?m:`${m} Esta sessão não conseguiu persistir alterações no navegador.`}
function projectEntries(){return[...grid.querySelectorAll(".project-card")].map(c=>({id:c.dataset.projectId||(c.querySelector("h3")?.textContent||"project").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,""),name:c.querySelector("h3")?.textContent?.trim()||"Ambiente",registryOrder:Number.isFinite(Number(c.dataset.projectOrder))?Number(c.dataset.projectOrder):Number.MAX_SAFE_INTEGER}))}
function defaultOrder(){return projectEntries().slice().sort((a,b)=>a.registryOrder-b.registryOrder||a.name.localeCompare(b.name,"pt-BR")).map(x=>x.id)}function normalizedOrder(){const e=projectEntries(),ids=e.map(x=>x.id),d=defaultOrder(),s=readJson(O,[]),v=Array.isArray(s)?s.filter(id=>typeof id==="string"&&ids.includes(id)):[];return[...new Set(v),...d.filter(id=>ids.includes(id)&&!v.includes(id))]}
function applyDensity(v,p=false){const n=["comfortable","compact"].includes(v)?v:"comfortable";density.value=n;document.documentElement.classList.toggle("density-compact",n==="compact");if(p){writeText(D,n);announce(`Densidade ${n==="compact"?"compacta":"confortável"} aplicada.`)}}function applyTechnical(v,p=false){const n=["show","hide"].includes(v)?v:"show";technical.checked=n==="show";document.documentElement.classList.toggle("technical-cards-hidden",n==="hide");if(p){writeText(T,n);announce(n==="show"?"Detalhes técnicos dos cards exibidos.":"Detalhes técnicos dos cards ocultados.")}}
const refreshCatalog=()=>document.dispatchEvent(new CustomEvent("central:catalog-refresh"));function saveOrder(o){writeJson(O,o);writeText(S,"default");if(catalogSort)catalogSort.value="default";refreshCatalog()}function moveProject(id,d){const o=normalizedOrder(),i=o.indexOf(id),t=i+d;if(i<0||t<0||t>=o.length)return;[o[i],o[t]]=[o[t],o[i]];saveOrder(o);renderOrder();announce("Ordem dos ambientes atualizada. O catálogo voltou para Ordem padrão.")}
function renderOrder(){if(renderingOrder)return;renderingOrder=true;try{const e=projectEntries(),by=new Map(e.map(x=>[x.id,x])),o=normalizedOrder().filter(id=>by.has(id));orderList.innerHTML="";o.forEach((id,i)=>{const item=by.get(id),row=document.createElement("div");row.className="preference-order-item";row.innerHTML=`<span class="preference-order-name">${escapeHtml(item.name)}</span><span class="preference-order-actions"><button class="preference-order-button" type="button" data-move="-1" aria-label="Mover ${escapeHtml(item.name)} para cima" ${i===0?"disabled":""}>↑</button><button class="preference-order-button" type="button" data-move="1" aria-label="Mover ${escapeHtml(item.name)} para baixo" ${i===o.length-1?"disabled":""}>↓</button></span>`;row.querySelectorAll("[data-move]").forEach(b=>b.addEventListener("click",()=>moveProject(id,Number(b.dataset.move))));orderList.appendChild(row)})}finally{renderingOrder=false}}
function resetPreferences(){if(!window.confirm("Restaurar foco, favoritos, ordem, densidade e preferências de apresentação aos padrões? O histórico de último acesso será preservado."))return;[D,T,O,S,F,FO].forEach(removeKey);applyDensity("comfortable");applyTechnical("show");if(catalogSort)catalogSort.value="default";const o=defaultOrder();if(o.length)writeJson(O,o);refreshCatalog();renderOrder();announce("Preferências restauradas. O histórico de último acesso foi preservado.");setTimeout(()=>location.reload(),250)}
const sd=readText(D),st=readText(T);if(sd&&!["comfortable","compact"].includes(sd))removeKey(D);if(st&&!["show","hide"].includes(st))removeKey(T);applyDensity(["comfortable","compact"].includes(sd)?sd:"comfortable");applyTechnical(["show","hide"].includes(st)?st:"show");density.addEventListener("change",()=>applyDensity(density.value,true));technical.addEventListener("change",()=>applyTechnical(technical.checked?"show":"hide",true));reset.addEventListener("click",resetPreferences);renderOrder();new MutationObserver(()=>{if(!renderingOrder)queueMicrotask(renderOrder)}).observe(grid,{childList:true,subtree:false});announce(storageWritable?"Preferências salvas somente neste navegador.":"Preferências aplicadas apenas nesta sessão.");
})();